### ISSUE TITLE
Strange bug in preprocessor

### ISSUE THREAD

**Issue by mcatkins** [CTSRD-CHERI/llvm-project#722] opened 2023-10-02 11:32 UTC
With the Morello clang:
```
$ clang -E -P -
#ifndef AA
AA: A
#endif

#ifdef U1
#endif

#ifdef U2
#endif

xxx
```
outputs:
```
AA: A xxx
```

But with clang 14.0.0 from Ubuntu, it outputs:
```
AA: A
xxx
```

Note two lines, verses one.

Martin

**Comment by brooksdavis** [comment] 2023-10-02 15:17
This bug is present in morello-llvm, but not in cheri-llvm. I've also verified that it's an am armv8-a bug on compiler explorer. It should be submitted to https://git.morello-project.org/morello/llvm-project/-/issues for Arm's attention.

https://cheri-compiler-explorer.cl.cam.ac.uk/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1AB9U8lJL6yAngGVG6AMKpaAVxYMQ0hwBk8DTAA5dwAjTGIJLlIAB1QFQlsGZzcPLxi4hIE/AOCWMIiuKMtMa0ShAiZiAmT3T2li0oFyyoJsoNDwyIsKqprU%2Bp7W/3a8zsKASgtUV2Jkdg4AUgAmAGY8KgYsKgBqAEFdhY193ZA9w4PVh3Xzm9X1re25LluVq6obo%2BW1qge5JZe3h9dqoQRxJrROABWXieDhaUioTiObYKaazTDbL48UgETRgyYAaxAKxWADoSRTKVSAGz6TiSGF4hGcXgKEAaHF4yZwWBINAsaJ0cLkSj8wX0CIsEiYWi0VAAWgQAE8QsQ8OhSFgAG54OYANTwmAA7gB5aKMTjYmi0AjhNkQEJMkL%2BSpKy28Z3MYhKk0hbQlXHcXj8tiCE0MWhuuG8LAhVzARxiWhsoOazAsQzAcTRzV4YgBvBazAp%2BGYVQlVy293kQQypm0PCq13OLBMghqljuyZUAzABQG41mi2p/iCERidhSGSCRQqdQ53RRAxGECmYzmBshNmQSaoaI2AQp%2BXYbby5S8VBF4hqrDbiCTBoHzwQBx9TxRXzDXL5PSxeJPt9fwyJ82m/MYLBlAsmkGQCikgxoGGaKpQI6ApuhaWD0OQr9UIkB80TmPC6Q4aFSFheFEQ4bYAAkVRvbYAFlpVlVBtggXBCBITFVi4cZeEDLRxkJYkySpMSKVpCEOAZMimUo1l2U5aNuRgRAQGmAhokrEUIDFIViECVh5mUGYSiYaJGOYuVeEwfAiBvPRR2EURxCnJzZzUJlF1II1iHMrtiNI8iL04E1Ky0ghtlQHZaNVdVLPzFi2OcAV9O4lZeP4rlhJJclxLE4iZOC5kOAUjkBPxYilkZHN5KUwTJiveI7EkIA

**Comment by jrtc27** [comment] 2023-10-02 15:36
You’ve hit the case that was fixed in https://github.com/llvm/llvm-project/commit/c6b0b16c0f55c34f4eaa05184815bbbe97f4b750 upstream, it seems. Not a bug in CHERI LLVM, and won’t be a bug in Morello LLVM once updated to 14.

**Closed by jrtc27** 2023-10-02 15:36 UTC
