### ISSUE TITLE
clang::SourceLocation clang::DeclSpec::getTypeSpecTypeNameLoc() const: Assertion `isDeclRep((TST) TypeSpecType) || TypeSpecType == TST_typename' failed.

### ISSUE THREAD

**Issue by tmarkettos** [CTSRD-CHERI/llvm-project#713] opened 2023-08-22 16:41 UTC
Attempting to build CheriBSD kernels ( ddbd02fd48c97a04195f4c58655ac481295355f4 ) with cheribuild ( f2b15a04a52d8afa42a367c9756dd5440d9fd3ad ) on Ubuntu 20.04, I get the above assertion failure in LLVM (ed9d9964fb200af225739a89bfb988cbe8d8f69e).

Command line:

```
./cheribuild.py run-dm-riscv64-purecap \
"--run-dm-riscv64-purecap/extra-options=-smp 2 -serial mon:stdio -serial pty -accel tcg,thread=multi -device virtio-net-device,netdev=net0 -netdev tap,id=net0,ifname=tap0,script=no,downscript=no -D trace.log" \
-d --skip-world \
--cheribsd/git-revision=device-model-riscv \
--qemu/git-revision=concurrent_tags_rebased_dm \
--qemu/targets="riscv64-softmmu,riscv64cheri-softmmu,riscv32-softmmu,riscv32cheri-softmmu" \
--bbl/git-revision=cheri_purecap_dm
```

Output files:
[freebsd64_uipc-92d11c.sh.txt](https://github.com/CTSRD-CHERI/llvm-project/files/12410728/freebsd64_uipc-92d11c.sh.txt)
[freebsd64_uipc-92d11c.c.txt](https://github.com/CTSRD-CHERI/llvm-project/files/12410729/freebsd64_uipc-92d11c.c.txt)

Log:
```
Building kernels for configs: CHERI-QEMU CHERI-PURECAP-QEMU
cd /home/atm26/cheri/cheribsd && env MAKEOBJDIRPREFIX=/home/atm26/cheri/build/cheribsd-riscv64-purecap-build CC=/usr/bin/clang-10 CXX=/usr/bin/clang++-10 CPP=/usr/bin/clang-cpp-10 STRIPBIN=/usr/bin/strip XCC=/home/atm26/cheri/output/sdk/bin/clang XCXX=/home/atm26/cheri/output/sdk/bin/clang++ XCPP=/home/atm26/cheri/output/sdk/bin/clang-cpp X_COMPILER_TYPE=clang XLD=/home/atm26/cheri/output/sdk/bin/ld.lld nice /home/atm26/cheri/cheribsd/tools/build/make.py -j16 buildkernel TARGET=riscv TARGET_ARCH=riscv64c TARGET_CPUTYPE=cheri -DDB_FROM_SRC -DI_REALLY_MEAN_NO_CLEAN -DNO_ROOT -DBUILD_WITH_STRICT_TMPPATH 'LOCAL_XTOOL_DIRS=lib/libnetbsd lib/libsbuf usr.sbin/makefs usr.bin/mkimg' LD=/home/atm26/cheri/output/sdk/bin/ld.lld XLD=/home/atm26/cheri/output/sdk/bin/ld.lld AR=/home/atm26/cheri/output/sdk/bin/llvm-ar NM=/home/atm26/cheri/output/sdk/bin/llvm-nm OBJCOPY=/home/atm26/cheri/output/sdk/bin/llvm-objcopy RANLIB=/home/atm26/cheri/output/sdk/bin/llvm-ranlib SIZE=/home/atm26/cheri/output/sdk/bin/llvm-size STRINGS=/home/atm26/cheri/output/sdk/bin/llvm-strings STRIPBIN=/home/atm26/cheri/output/sdk/bin/llvm-strip 'KERNCONF=CHERI-QEMU CHERI-PURECAP-QEMU' DEBUG=-g -DWITHOUT_CLEAN -DWITH_TESTS -DWITH_CHERI -DWITHOUT_INIT_ALL_ZERO -DWITHOUT_INIT_ALL_PATTERN -DWITHOUT_MAN -DWITHOUT_MAIL -DWITHOUT_PROFILE -DWITHOUT_OFED -DWITH_MALLOC_PRODUCTION -DWITHOUT_GCC -DWITHOUT_CLANG -DWITHOUT_LLD -DWITHOUT_LLDB -DWITHOUT_GCC_BOOTSTRAP -DWITHOUT_CLANG_BOOTSTRAP -DWITHOUT_LLD_BOOTSTRAP -DWITHOUT_LIB32 -DWITH_ELFTOOLCHAIN_BOOTSTRAP -DWITH_TOOLCHAIN -DWITHOUT_BINUTILS_BOOTSTRAP -s -de
bmake[1]: "/home/atm26/cheri/cheribsd/share/mk/bsd.linker.mk" line 78: warning: "/home/atm26/cheri/cheribsd: Rerunning /home/atm26/cheri/output/sdk/bin/ld.lld -v to compute LINKER_TYPE/LINKER_VERSION. This value should be cached!"
>>> Kernel build for CHERI-QEMU started on Tue Aug 22 16:17:16 UTC 2023
>>> stage 1: configuring the kernel
Kernel build directory is /home/atm26/cheri/build/cheribsd-riscv64-purecap-build/home/atm26/cheri/cheribsd/riscv.riscv64c/sys/CHERI-QEMU
Don't forget to do ``make cleandepend && make depend''
bmake[2]: "/home/atm26/cheri/cheribsd/share/mk/bsd.linker.mk" line 78: warning: "/home/atm26/cheri/cheribsd: Rerunning /home/atm26/cheri/output/sdk/bin/ld.lld -v to compute LINKER_TYPE/LINKER_VERSION. This value should be cached!"
>>> stage 2.3: build tools
bmake[2]: "/home/atm26/cheri/cheribsd/share/mk/bsd.linker.mk" line 78: warning: "/home/atm26/cheri/cheribsd: Rerunning /home/atm26/cheri/output/sdk/bin/ld.lld -v to compute LINKER_TYPE/LINKER_VERSION. This value should be cached!"
>>> stage 3.1: building everything
/home/atm26/cheri/cheribsd/sys/cam/nvme/nvme_xpt.c:261:19: warning: variable 'path' set but not used [-Wunused-but-set-variable]
        struct cam_path *path;
                         ^
/home/atm26/cheri/cheribsd/sys/cam/nvme/nvme_xpt.c:315:13: warning: variable 'status' set but not used [-Wunused-but-set-variable]
        cam_status status;
                   ^
2 warnings generated.
clang: /home/atm26/cheri/llvm-project/clang/include/clang/Sema/DeclSpec.h:527: clang::SourceLocation clang::DeclSpec::getTypeSpecTypeNameLoc() const: Assertion `isDeclRep((TST) TypeSpecType) || TypeSpecType == TST_typename' failed.
PLEASE submit a bug report to https://github.com/CTSRD-CHERI/llvm-project/issues and include the crash backtrace, preprocessed source, and associated run script.
If you built clang from source, please provide a reduced test case by running:
        $LLVM_BUILD_DIR/bin/creduce_crash_testcase.py <reproducer>.sh
Stack dump:
0.      Program arguments: /home/atm26/cheri/output/sdk/bin/clang -target riscv64-unknown-freebsd13.0 --sysroot=/home/atm26/cheri/build/cheribsd-riscv64-purecap-build/home/atm26/cheri/cheribsd/riscv.riscv64c/tmp -B/home/atm26/cheri/build/cheribsd-riscv64-purecap-build/home/atm26/cheri/cheribsd/riscv.riscv64c/tmp/usr/bin -c -O2 -pipe -fno-strict-aliasing -g -nostdinc -I. -I/home/atm26/cheri/cheribsd/sys -I/home/atm26/cheri/cheribsd/sys/contrib/ck/include -I/home/atm26/cheri/cheribsd/sys/contrib/libfdt -D_KERNEL -DHAVE_KERNEL_OPTION_HEADERS -include opt_global.h -fno-common -fPIE -fno-omit-frame-pointer -fno-optimize-sibling-calls -MD -MF.depend.freebsd64_uipc.o -MTfreebsd64_uipc.o -fdebug-prefix-map=./machine=/home/atm26/cheri/cheribsd/sys/riscv/include -march=rv64imafdcxcheri -mabi=lp64 -mno-relax -ffreestanding -fwrapv -fstack-protector -gdwarf-2 -Wall -Wredundant-decls -Wnested-externs -Wstrict-prototypes -Wmissing-prototypes -Wpointer-arith -Wcast-qual -Wundef -Wno-pointer-sign -D__printf__=__freebsd_kprintf__ -Wmissing-include-dirs -fdiagnostics-show-option -Wno-unknown-pragmas -Wno-error=tautological-compare -Wno-error=empty-body -Wno-error=parentheses-equality -Wno-error=unused-function -Wno-error=pointer-sign -Wno-error=shift-negative-value -Wno-address-of-packed-member -Wno-error=unused-but-set-variable -Wno-format-zero-length -mcmodel=medium -std=iso9899:1999 -Werror /home/atm26/cheri/cheribsd/sys/compat/freebsd64/freebsd64_uipc.c
1.      /home/atm26/cheri/cheribsd/sys/compat/freebsd64/freebsd64_uipc.c:138:17 <Spelling=/home/atm26/cheri/cheribsd/sys/sys/param.h:397:45>: current parser token ')'
2.      /home/atm26/cheri/cheribsd/sys/compat/freebsd64/freebsd64_uipc.c:121:1: parsing function body 'freebsd64_copyinmsghdr'
3.      /home/atm26/cheri/cheribsd/sys/compat/freebsd64/freebsd64_uipc.c:121:1: in compound statement ('{}')
4.      /home/atm26/cheri/cheribsd/sys/compat/freebsd64/freebsd64_uipc.c:138:17 <Spelling=/home/atm26/cheri/cheribsd/sys/sys/param.h:393:21>: in compound statement ('{}')
 #0 0x0000000002351843 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/atm26/cheri/output/sdk/bin/clang+0x2351843)
 #1 0x000000000234f56e llvm::sys::RunSignalHandlers() (/home/atm26/cheri/output/sdk/bin/clang+0x234f56e)
 #2 0x0000000002350bdd llvm::sys::CleanupOnSignal(unsigned long) (/home/atm26/cheri/output/sdk/bin/clang+0x2350bdd)
 #3 0x00000000022be433 (anonymous namespace)::CrashRecoveryContextImpl::HandleCrash(int, unsigned long) CrashRecoveryContext.cpp:0:0
 #4 0x00000000022be5de CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #5 0x00007f09532d9420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #6 0x00007f0952d6c00b raise /build/glibc-SzIz7B/glibc-2.31/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #7 0x00007f0952d4b859 abort /build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:81:7
 #8 0x00007f0952d4b729 get_sysdep_segment_value /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:509:8
 #9 0x00007f0952d4b729 _nl_load_domain /build/glibc-SzIz7B/glibc-2.31/intl/loadmsgcat.c:970:34
#10 0x00007f0952d5cfd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
#11 0x0000000003f0a527 clang::TypeLocVisitor<(anonymous namespace)::TypeSpecLocFiller, void>::Visit(clang::UnqualTypeLoc) SemaType.cpp:0:0
#12 0x0000000003f0d6b3 (anonymous namespace)::TypeSpecLocFiller::VisitElaboratedTypeLoc(clang::ElaboratedTypeLoc) SemaType.cpp:0:0
#13 0x0000000003ef6572 GetFullTypeForDeclarator((anonymous namespace)::TypeProcessingState&, clang::QualType, clang::TypeSourceInfo*) SemaType.cpp:0:0
#14 0x0000000003eee84e clang::Sema::GetTypeForDeclarator(clang::Declarator&, clang::Scope*) (/home/atm26/cheri/output/sdk/bin/clang+0x3eee84e)
#15 0x0000000003ef855a clang::Sema::ActOnTypeName(clang::Scope*, clang::Declarator&) (/home/atm26/cheri/output/sdk/bin/clang+0x3ef855a)
#16 0x0000000003647240 clang::Parser::ParseTypeName(clang::SourceRange*, clang::DeclaratorContext, clang::AccessSpecifier, clang::Decl**, clang::ParsedAttributes*) (/home/atm26/cheri/output/sdk/bin/clang+0x3647240)
#17 0x0000000003693f32 clang::Parser::ParseParenExpression(clang::Parser::ParenParseOption&, bool, bool, clang::OpaquePtr<clang::QualType>&, clang::SourceLocation&) (/home/atm26/cheri/output/sdk/bin/clang+0x3693f32)
#18 0x000000000368fb05 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/home/atm26/cheri/output/sdk/bin/clang+0x368fb05)
#19 0x000000000368b901 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/home/atm26/cheri/output/sdk/bin/clang+0x368b901)
#20 0x000000000368a13c clang::Parser::ParseAssignmentExpression(clang::Parser::TypeCastState) (/home/atm26/cheri/output/sdk/bin/clang+0x368a13c)
#21 0x000000000368a079 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/home/atm26/cheri/output/sdk/bin/clang+0x368a079)
#22 0x00000000036f9ad5 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/home/atm26/cheri/output/sdk/bin/clang+0x36f9ad5)
#23 0x00000000036f88c7 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributesWithRange&) (/home/atm26/cheri/output/sdk/bin/clang+0x36f88c7)
#24 0x00000000036f7931 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/home/atm26/cheri/output/sdk/bin/clang+0x36f7931)
#25 0x00000000037018a1 clang::Parser::ParseCompoundStatementBody(bool) (/home/atm26/cheri/output/sdk/bin/clang+0x37018a1)
#26 0x00000000036fb075 clang::Parser::ParseCompoundStatement(bool) (/home/atm26/cheri/output/sdk/bin/clang+0x36fb075)
#27 0x000000000369429d clang::Parser::ParseParenExpression(clang::Parser::ParenParseOption&, bool, bool, clang::OpaquePtr<clang::QualType>&, clang::SourceLocation&) (/home/atm26/cheri/output/sdk/bin/clang+0x369429d)
#28 0x000000000368fb05 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, bool&, clang::Parser::TypeCastState, bool, bool*) (/home/atm26/cheri/output/sdk/bin/clang+0x368fb05)
#29 0x000000000368b901 clang::Parser::ParseCastExpression(clang::Parser::CastParseKind, bool, clang::Parser::TypeCastState, bool, bool*) (/home/atm26/cheri/output/sdk/bin/clang+0x368b901)
#30 0x000000000368abe6 clang::Parser::ParseRHSOfBinaryExpression(clang::ActionResult<clang::Expr*, true>, clang::prec::Level) (/home/atm26/cheri/output/sdk/bin/clang+0x368abe6)
#31 0x000000000368a079 clang::Parser::ParseExpression(clang::Parser::TypeCastState) (/home/atm26/cheri/output/sdk/bin/clang+0x368a079)
#32 0x00000000036f9ad5 clang::Parser::ParseExprStatement(clang::Parser::ParsedStmtContext) (/home/atm26/cheri/output/sdk/bin/clang+0x36f9ad5)
#33 0x00000000036f88c7 clang::Parser::ParseStatementOrDeclarationAfterAttributes(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*, clang::ParsedAttributesWithRange&) (/home/atm26/cheri/output/sdk/bin/clang+0x36f88c7)
#34 0x00000000036f7931 clang::Parser::ParseStatementOrDeclaration(llvm::SmallVector<clang::Stmt*, 32u>&, clang::Parser::ParsedStmtContext, clang::SourceLocation*) (/home/atm26/cheri/output/sdk/bin/clang+0x36f7931)
#35 0x00000000037018a1 clang::Parser::ParseCompoundStatementBody(bool) (/home/atm26/cheri/output/sdk/bin/clang+0x37018a1)
#36 0x00000000037029c8 clang::Parser::ParseFunctionStatementBody(clang::Decl*, clang::Parser::ParseScope&) (/home/atm26/cheri/output/sdk/bin/clang+0x37029c8)
#37 0x00000000036392e5 clang::Parser::ParseFunctionDefinition(clang::ParsingDeclarator&, clang::Parser::ParsedTemplateInfo const&, clang::Parser::LateParsedAttrList*) (/home/atm26/cheri/output/sdk/bin/clang+0x36392e5)
#38 0x000000000365a24f clang::Parser::ParseDeclGroup(clang::ParsingDeclSpec&, clang::DeclaratorContext, clang::SourceLocation*, clang::Parser::ForRangeInit*) (/home/atm26/cheri/output/sdk/bin/clang+0x365a24f)
#39 0x00000000036385be clang::Parser::ParseDeclOrFunctionDefInternal(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec&, clang::AccessSpecifier) (/home/atm26/cheri/output/sdk/bin/clang+0x36385be)
#40 0x0000000003638055 clang::Parser::ParseDeclarationOrFunctionDefinition(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*, clang::AccessSpecifier) (/home/atm26/cheri/output/sdk/bin/clang+0x3638055)
#41 0x0000000003636d6a clang::Parser::ParseExternalDeclaration(clang::ParsedAttributesWithRange&, clang::ParsingDeclSpec*) (/home/atm26/cheri/output/sdk/bin/clang+0x3636d6a)
#42 0x0000000003634d9f clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, bool) (/home/atm26/cheri/output/sdk/bin/clang+0x3634d9f)
#43 0x000000000362f4ed clang::ParseAST(clang::Sema&, bool, bool) (/home/atm26/cheri/output/sdk/bin/clang+0x362f4ed)
#44 0x0000000002d0d400 clang::FrontendAction::Execute() (/home/atm26/cheri/output/sdk/bin/clang+0x2d0d400)
#45 0x0000000002c840f8 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/home/atm26/cheri/output/sdk/bin/clang+0x2c840f8)
#46 0x0000000002dc60b3 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/home/atm26/cheri/output/sdk/bin/clang+0x2dc60b3)
#47 0x000000000098936b cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/home/atm26/cheri/output/sdk/bin/clang+0x98936b)
#48 0x0000000000987140 ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&) driver.cpp:0:0
#49 0x0000000002b01f52 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const::$_1>(long) Job.cpp:0:0
#50 0x00000000022be351 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/home/atm26/cheri/output/sdk/bin/clang+0x22be351)
#51 0x0000000002b01950 clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/home/atm26/cheri/output/sdk/bin/clang+0x2b01950)
#52 0x0000000002ac8fe4 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/home/atm26/cheri/output/sdk/bin/clang+0x2ac8fe4)
#53 0x0000000002ac9527 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/home/atm26/cheri/output/sdk/bin/clang+0x2ac9527)
#54 0x0000000002ae4f5b clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/home/atm26/cheri/output/sdk/bin/clang+0x2ae4f5b)
#55 0x0000000000986a79 main (/home/atm26/cheri/output/sdk/bin/clang+0x986a79)
#56 0x00007f0952d4d083 __libc_start_main /build/glibc-SzIz7B/glibc-2.31/csu/../csu/libc-start.c:342:3
#57 0x0000000000983fae _start (/home/atm26/cheri/output/sdk/bin/clang+0x983fae)
clang-14: error: clang frontend command failed with exit code 134 (use -v to see invocation)
clang version 14.0.0 (https://github.com/CTSRD-CHERI/llvm-project.git ed9d9964fb200af225739a89bfb988cbe8d8f69e)
Target: riscv64-unknown-freebsd13.0
Thread model: posix
InstalledDir: /home/atm26/cheri/output/sdk/bin
/home/atm26/cheri/cheribsd/sys/cam/cam_periph.c:1168:3: warning: memmove operation with capability argument 'union ccb' and underaligned destination (aligned to 1 bytes) may be inefficient or result in CHERI tags bits being stripped [-Wcheri-inefficient]
                bcopy(ccb, addr, sizeof(union ccb));
                ^
/home/atm26/cheri/cheribsd/sys/cam/cam_periph.c:1168:3: note: use __builtin_assume_aligned() or cast to (u)intcap_t* if you know that the pointer is actually aligned to capability size; this will allow the memcpy() or memmove() call to be inlined if the size is constant (otherwise a library call must be used to maintain tag bits). For more information see https://github.com/CTSRD-CHERI/llvm-project/wiki/Unaligned-capability-copies
clang-14: note: diagnostic msg: 
********************
PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang-14: note: diagnostic msg: /tmp/freebsd64_uipc-92d11c.c
clang-14: note: diagnostic msg: /tmp/freebsd64_uipc-92d11c.sh
clang-14: note: diagnostic msg: 
********************
--- freebsd64_uipc.o ---
*** [freebsd64_uipc.o] Error code 134
bmake[2]: stopped in /home/atm26/cheri/build/cheribsd-riscv64-purecap-build/home/atm26/cheri/cheribsd/riscv.riscv64c/sys/CHERI-QEMU
1 warning generated.
--- all_subdir_accf_http ---
--- modules-all ---
*** [modules-all] Error code 2
bmake[2]: stopped in /home/atm26/cheri/build/cheribsd-riscv64-purecap-build/home/atm26/cheri/cheribsd/riscv.riscv64c/sys/CHERI-QEMU
2 errors
bmake[2]: stopped in /home/atm26/cheri/build/cheribsd-riscv64-purecap-build/home/atm26/cheri/cheribsd/riscv.riscv64c/sys/CHERI-QEMU
--- buildkernel ---
--- buildkernel ---
Fatal error (in target cheribsd-riscv64-purecap): Command `nice /home/atm26/cheri/cheribsd/tools/build/make.py -j16 buildkernel TARGET=riscv TARGET_ARCH=riscv64c TARGET_CPUTYPE=cheri -DDB_FROM_SRC -DI_REALLY_MEAN_NO_CLEAN -DNO_ROOT -DBUILD_WITH_STRICT_TMPPATH 'LOCAL_XTOOL_DIRS=lib/libnetbsd lib/libsbuf usr.sbin/makefs usr.bin/mkimg' LD=/home/atm26/cheri/output/sdk/bin/ld.lld XLD=/home/atm26/cheri/output/sdk/bin/ld.lld AR=/home/atm26/cheri/output/sdk/bin/llvm-ar NM=/home/atm26/cheri/output/sdk/bin/llvm-nm OBJCOPY=/home/atm26/cheri/output/sdk/bin/llvm-objcopy RANLIB=/home/atm26/cheri/output/sdk/bin/llvm-ranlib SIZE=/home/atm26/cheri/output/sdk/bin/llvm-size STRINGS=/home/atm26/cheri/output/sdk/bin/llvm-strings STRIPBIN=/home/atm26/cheri/output/sdk/bin/llvm-strip 'KERNCONF=CHERI-QEMU CHERI-PURECAP-QEMU' DEBUG=-g -DWITHOUT_CLEAN -DWITH_TESTS -DWITH_CHERI -DWITHOUT_INIT_ALL_ZERO -DWITHOUT_INIT_ALL_PATTERN -DWITHOUT_MAN -DWITHOUT_MAIL -DWITHOUT_PROFILE -DWITHOUT_OFED -DWITH_MALLOC_PRODUCTION -DWITHOUT_GCC -DWITHOUT_CLANG -DWITHOUT_LLD -DWITHOUT_LLDB -DWITHOUT_GCC_BOOTSTRAP -DWITHOUT_CLANG_BOOTSTRAP -DWITHOUT_LLD_BOOTSTRAP -DWITHOUT_LIB32 -DWITH_ELFTOOLCHAIN_BOOTSTRAP -DWITH_TOOLCHAIN -DWITHOUT_BINUTILS_BOOTSTRAP -s -de` failed with non-zero exit code 2
```

Attempting to run creduce_crash_testcase.py only gets me:
```
$ ~/cheri/llvm-project/clang/utils/creduce_crash_testcase.py /tmp/freebsd64_uipc-92d11c.sh
Install the ansicolors package for coloured output.
Did not find FileCheck in @CMAKE_BINARY_DIR@/bin
```

**Comment by jrtc27** [comment] 2023-08-22 19:43
It shouldn't crash like that, but given the age of the branch you're likely to have other issues. Reducing now.

**Comment by jrtc27** [comment] 2023-08-22 19:49
Turns out to be a duplicate of #710

**Closed by jrtc27** 2023-08-22 19:49 UTC
